spring:
  shardingsphere:
    datasource:
      names: db0,db1

      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db0?serverTimezone=CTT&characterEncoding=utf-8
        username: root
        password: root
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db1?serverTimezone=CTT&characterEncoding=utf-8
        username: root
        password: root

    props:
      sql:
        show: true

    sharding:
      tables:
        users:
          actual-data-nodes: db$->{0..1}.users_$->{0..1} # 配置数据库和表
          database-strategy:
            inline:
              # 配置根据哪个字段选择数据库
              sharding-column: id
              # 配置选择哪个数据库的规则
              algorithm-expression: db$->{id % 2}

          table-strategy:
            inline:
              # 配置根据哪个字段选择表
              sharding-column: id
              # 配置选择哪个表的规则
              algorithm-expression: users_$->{(Integer)(id / 2) % 4}

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8881